steps:
  # Backend Docker build & push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/supportsync-39f6b/crm-backend', './backend']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/supportsync-39f6b/crm-backend']
  
  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'crm-backend'
      - '--image'
      - 'gcr.io/supportsync-39f6b/crm-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '5000'
      - '--set-secrets'
      - 'MONGODB_URI=MONGODB_URI:latest,REDIS_HOST=REDIS_HOST:latest,REDIS_PORT=REDIS_PORT:latest,JWT_SECRET=JWT_SECRET:latest'

  - name: 'node:20'
    entrypoint: npm
    args: ['install']
    dir: 'frontend'
  
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    dir: 'frontend'

  # Firebase deploy (original)
  - name: 'node:20'
    entrypoint: npm
    args: ['install', '-g', 'firebase-tools']
    dir: 'frontend'

  - name: 'node:20'
    entrypoint: firebase
    args:
      - 'deploy'
      - '--only'
      - 'hosting'
      - '--project'
      - 'supportsync-39f6b'
      - '--token'
      - '$$FIREBASE_TOKEN'
    dir: 'frontend'
    secretEnv: ['FIREBASE_TOKEN']

availableSecrets:
  secretManager:
  - versionName: projects/supportsync-39f6b/secrets/FIREBASE_TOKEN/versions/latest
    env: 'FIREBASE_TOKEN'

images:
  - 'gcr.io/supportsync-39f6b/crm-backend'

options:
  logging: CLOUD_LOGGING_ONLY