steps:
  # Build the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/crm-gira/crm-backend', './backend']
  
  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/crm-gira/crm-backend']
  
  # Deploy to Cloud Run with secrets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'crm-backend'
      - '--image'
      - 'gcr.io/crm-gira/crm-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '5000'
      - '--set-secrets'
      - 'MONGODB_URI=MONGODB_URI:latest,REDIS_HOST=REDIS_HOST:latest,REDIS_PORT=REDIS_PORT:latest,JWT_SECRET=JWT_SECRET:latest'

  # Build and deploy frontend
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: npm
    args: ['install']
    dir: 'frontend'
  
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: npm
    args: ['run', 'build']
    dir: 'frontend'
  
  # Install Firebase CLI and deploy
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: sh
    args:
      - -c
      - |
        npm install -g firebase-tools
        export PATH=$PATH:$(npm bin -g)
        firebase deploy --only hosting --project supportsyncv2
    dir: 'frontend'

images:
  - 'gcr.io/crm-gira/crm-backend'

options:
  logging: CLOUD_LOGGING_ONLY



