steps:
  # ----------------------------
  # BACKEND: Build & Deploy to Cloud Run
  # ----------------------------
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args: ['build', '-t', 'gcr.io/crm-gira/crm-backend', './backend']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args: ['push', 'gcr.io/crm-gira/crm-backend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'crm-backend'
      - '--image=gcr.io/crm-gira/crm-backend'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-secrets=MONGODB_URI=MONGODB_URI:latest'
      - '--set-secrets=REDIS_HOST=REDIS_HOST:latest'
      - '--set-secrets=REDIS_PORT=REDIS_PORT:latest'
      - '--set-secrets=JWT_SECRET=JWT_SECRET:latest'
    # Uncomment if you need env vars (non-secrets):
    # - '--set-env-vars=ENV=production'

  # ----------------------------
  # FRONTEND: Build & Deploy to Firebase Hosting
  # ----------------------------
  - name: 'gcr.io/cloud-builders/npm'
    id: 'install-frontend'
    args: ['install']
    dir: 'frontend'

  - name: 'gcr.io/cloud-builders/npm'
    id: 'build-frontend'
    args: ['run', 'build']
    dir: 'frontend'

  - name: 'gcr.io/firebase-ci/firebase'
    id: 'deploy-frontend'
    args: ['deploy', '--only', 'hosting']
    dir: 'frontend'

# ----------------------------
# OPTIONS
# ----------------------------
options:
  logging: CLOUD_LOGGING_ONLY
  diskSizeGb: 20  # Larger disk for caching

images:
  - 'gcr.io/crm-gira/crm-backend'